version: "3"

services:
  cosftpd-devel:
    image: hzcsk8s.io/cosftpd-devel
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev

  cosftpd:
    image: hzcsk8s.io/cosftpd
    container_name: cosftpd
    hostname: cosftpd
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.cosftpd
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    # restart: always
    # env_file:
    #   - ./.env
    environment:
      FTP_USER: holyhand
      FTP_PASS: holyhand
      LOG_STDOUT: 1  
      PASV_ADDRESS: ${EXTERNAL_IP:-0.0.0.0}
      PASV_MIN_PORT: ${PASV_MIN_PORT}
      PASV_MAX_PORT: ${PASV_MAX_PORT}
      COS_SECRETID: AKIDV7XjgOr42nMhneGdmiPs66rNioeFafeT
      COS_SECRETKEY: d190cxQk0CHCtLXjhQt65tUr2yf7KI1V
      COS_ENDPOINT: cos.ap-beijing.myqcloud.com
      COS_APPID: 1301930378
      COS_BUCKET_NAME: cosftpd-1301930378
      HTTP_SERVER_API: ${HTTP_SERVER_API}
    ports:
      - "20:20"
      - "21:21"
      - "${PASV_MIN_PORT}-${PASV_MAX_PORT}:${PASV_MIN_PORT}-${PASV_MAX_PORT}"
    volumes:
      - ./home:/home/vsftpd
      - ./logs:/var/log/vsftpd
      - ./app/src:/app/src
      - ./scripts/entrypoint.sh:/entrypoint.sh
      - ./scripts/run-vsftpd.sh:/app/bin/run-vsftpd.sh
    entrypoint: /entrypoint.sh
    network_mode: bridge
